name: Build and Deploy

on:
  push:
    branches:
      - main  # Puedes cambiar esto según tus necesidades

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: valkimialearning

      - name: Build Docker image
        run: docker build -t valkimia-learning-imagen .

      - name: Configure Docker authentication
        run: gcloud auth configure-docker

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/valkimialearning/valkimia-learning-imagen:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy valkimia-learning-servicio \
            --image gcr.io/valkimialearning/valkimia-learning-imagen:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
